sudo: required
services:
  - docker

before_install:
  - gem install fpm package_cloud

script:
  - docker-compose -f docker-compose.test.yml up|grep "heroku"
  - docker-compose -f docker-compose.test.yml up|grep "Composer version"
  - make push-deb

notifications:
  email: docker@katagena.com
