version: '3'

services:
  heroku:
    build: .
    image: nouchka/heroku:latest
    stdin_open: true
    tty: true
    volumes:
      - ./project/:/workspace/
      - root:/root/

volumes:
  root:
    driver: local

